
// auth actions
export const DO_GENERATE_PUZZLE = 'DO_GENERATE_PUZZLE';

export const DO_RESOLVE_PUZZLE_BFS = 'DO_RESOLVE_PUZZLE_BFS';
export const DO_RESOLVE_PUZZLE_ASTAR = 'DO_RESOLVE_PUZZLE_ASTAR';
export const DO_RESOLVE_PUZZLE_SUCCESS = 'DO_RESOLVE_PUZZLE_SUCCESS';
export const DO_RESOLVE_PUZZLE_ERROR = 'DO_RESOLVE_PUZZLE_ERROR';

export const DO_MAKE_MOVE = 'DO_MAKE_MOVE';

export const DO_START_GAME = 'DO_START_GAME';

export const DO_MAKE_MOVE_CONNECT = 'DO_MAKE_MOVE_CONNECT';
export const DO_MAKE_MOVE_CONNECT_SUCCESS = 'DO_MAKE_MOVE_CONNECT_SUCCESS';
export const DO_MAKE_MOVE_CONNECT_ERROR = 'DO_MAKE_MOVE_CONNECT_ERROR';

export const DO_NEW_CONNECT_GAME = 'DO_NEW_CONNECT_GAME';
export const DO_NEW_CONNECT_GAME_SUCCESS = 'DO_NEW_CONNECT_GAME_SUCCESS';
export const DO_NEW_CONNECT_GAME_ERROR = 'DO_NEW_CONNECT_GAME_ERROR';

export const DO_NEW_N_QUEEN_GAME = 'DO_NEW_N_QUEEN_GAME';

export const DO_RESOLVE_N_QUEEN_GAME = 'DO_RESOLVE_N_QUEEN_GAME';
export const DO_RESOLVE_N_QUEEN_GAME_SUCCESS = 'DO_RESOLVE_N_QUEEN_GAME_SUCCESS';
export const DO_RESOLVE_N_QUEEN_GAME_ERROR = 'DO_RESOLVE_N_QUEEN_GAME_ERROR';

export const DO_UPDATE_MOVE_N_QUEEN_GAME = 'DO_UPDATE_MOVE_N_QUEEN_GAME';
